//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompetenciesWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competence
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Time { get; set; }
        public string Picture { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
    }
}
